---
common: []
rpms:
  - nfs-utils
  - yum-utils
  - bind-utils
  - glusterfs-fuse
  - lz4
  - nss
  - nss-sysinit
  - nss-tools
  - conntrack-tools
debs: []
centos: []

centos7:
  - libselinux-python

debian: []

debian10: []

debian11: []

ubuntu: []

ubuntu1804: []

ubuntu2004:


# The minimum version of docker-ce on ubuntu 2204 is 20.10.13
ubuntu2204:
  - fcitx5
  - fcitx5-chewing
  - fcitx5-chinese-addons
  - fcitx5-frontend-gtk2
  - fcitx5-frontend-gtk3
  - fcitx5-frontend-gtk4
  - fcitx5-frontend-qt5
  - fonts-arphic-ukai
  - fonts-arphic-uming
  - fonts-beng
  - fonts-deva
  - fonts-farsiweb
  - fonts-gujr
  - fonts-guru
  - fonts-khmeros
  - fonts-knda
  - fonts-lao
  - fonts-manchufont
  - fonts-mlym
  - fonts-nafees
  - fonts-noto-cjk
  - fonts-noto-cjk-extra
  - fonts-noto-core
  - fonts-noto-ui-core
  - fonts-orya
  - fonts-sil-ezra
  - fonts-sil-padauk
  - fonts-sil-scheherazade
  - fonts-taml
  - fonts-telu
  - fonts-thai-tlwg
  - fonts-tibetan-machine
  - fonts-ukij-uyghur
  - gtk-im-libthai
  - gtk3-im-libthai
  - ibus-hangul
  - ibus-m17n
  - ibus-mozc
  - ibus-unikey
  - language-pack-af
  - language-pack-am
  - language-pack-an
  - language-pack-ar
  - language-pack-as
  - language-pack-ast
  - language-pack-az
  - language-pack-be
  - language-pack-bg
  - language-pack-bn
  - language-pack-br
  - language-pack-bs
  - language-pack-ca
  - language-pack-ckb
  - language-pack-crh
  - language-pack-cs
  - language-pack-cy
  - language-pack-da
  - language-pack-de
  - language-pack-dz
  - language-pack-el
  - language-pack-en
  - language-pack-eo
  - language-pack-es
  - language-pack-et
  - language-pack-eu
  - language-pack-fa
  - language-pack-fi
  - language-pack-fr
  - language-pack-fur
  - language-pack-ga
  - language-pack-gd
  - language-pack-gl
  - language-pack-gu
  - language-pack-he
  - language-pack-hi
  - language-pack-hr
  - language-pack-hu
  - language-pack-ia
  - language-pack-id
  - language-pack-is
  - language-pack-it
  - language-pack-ja
  - language-pack-ka
  - language-pack-kab
  - language-pack-kk
  - language-pack-km
  - language-pack-kn
  - language-pack-ko
  - language-pack-ku
  - language-pack-lt
  - language-pack-lv
  - language-pack-mk
  - language-pack-ml
  - language-pack-mr
  - language-pack-ms
  - language-pack-my
  - language-pack-nb
  - language-pack-nds
  - language-pack-ne
  - language-pack-nl
  - language-pack-nn
  - language-pack-oc
  - language-pack-or
  - language-pack-pa
  - language-pack-pl
  - language-pack-pt
  - language-pack-ro
  - language-pack-ru
  - language-pack-si
  - language-pack-sk
  - language-pack-sl
  - language-pack-sq
  - language-pack-sr
  - language-pack-sv
  - language-pack-szl
  - language-pack-ta
  - language-pack-te
  - language-pack-tg
  - language-pack-th
  - language-pack-tr
  - language-pack-ug
  - language-pack-uk
  - language-pack-vi
  - language-pack-xh
  - language-pack-zh-hans
  - language-pack-zh-hant
  - libenchant-2-voikko
  - mozc-utils-gui
  - voikko-fi
  - wamerican
  - wbrazilian
  - wbritish
  - wbulgarian
  - wcatalan
  - wdanish
  - wdutch
  - wfaroese
  - wfrench
  - wgaelic
  - wgalician-minimos
  - wirish
  - witalian
  - wmanx
  - wngerman
  - wnorwegian
  - wogerman
  - wpolish
  - wportuguese
  - wspanish
  - wswedish
  - wswiss
  - wukrainian
  
almalinux: []

almalinux90: []
