name: gen-repository-iso-22.04
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-22.04-debs
            dockerfile: dockerfile.ubuntu2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build iso image to local
        uses: docker/build-push-action@v6
        with:
          context: hack/gen-repository-iso
          file: hack/gen-repository-iso/${{ matrix.dockerfile }}
          platforms: linux/amd64
          outputs: type=local,dest=./output
      - name: create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./output/*.z
            ./output/packages.*
          tag_name: ${{ github.event.inputs.tags }}
